version: '3.8'

services:
  service:
    container_name: project-template-service
    build:
      context: .
      dockerfile: docker/service.dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - project-template

  database:
    image: postgres:13
    container_name: project-template-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project-template
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - project-template

volumes:
  postgres-data:
    driver: local

networks:
  project-template: